### ISSUE TITLE
When enemy is killed it still technically exists, although it is not visible.

### ISSUE THREAD

**Issue by oboat9** [SelectedAll/Pygame#1]

**Comment by LeoFoco** [comment]
Stop making fun of me

**Comment by oboat9** [comment]
I am just stating a fact that there is a bug in the code that you will need to fix, there is no fun being made of (this is not English class don't worry)

**Comment by LeoFoco** [comment]
It was a joek

**Comment by oboat9** [comment]
this is still an issue, please get to fixing this

**Comment by LeoFoco** [comment]
finally fixed (mostly)
